### ISSUE TITLE
Whitespace/Comments

### ISSUE THREAD

**Issue by matthewhammer** [dfinity/motoko.rs#6]
For our project, we want comments to be retained in the AST, to retain them in the formatted output.

For lalrpop, need to preprocess input to make whitespace in comments parseable.  Maybe other steps are needed too.

**Comment by rvanasa** [comment]
https://github.com/lalrpop/lalrpop/issues/14
https://github.com/lalrpop/lalrpop/pull/509

**Comment by matthewhammer** [comment]
See #11
